export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

export const SING_UP_REQUEST = 'SING_UP_REQUEST';
export const SING_UP_SUCCESS = 'SING_UP_SUCCESS';
export const SING_UP_FAILURE = 'SING_UP_FAILURE';
